### PR TITLE
macOS dependencies for Cycles

### PR DESCRIPTION
**Pull request by up4**
Hi I'm slowly trying to understand the Cycles standalone code base and I wanted to compile the dependencies myself instead of pulling the precompiled binaries from SVN. I updated permanently unreachable URLs (but not versions) for HDF 1.8.17 and Schroedinger 1.0.11. Upgraded Boost from 1.60 to 1.62, FFMPEG from 3.2.1 to 3.2.2 and OIIO from 1.7.8 to 1.7.9.

I have committed a workaround patch for Python for a known compilation problem only seen on macOS X.

I'm stuck with OpenVDB. They don't keep archives for the zip file you are using and the [file they do archive on Github](https://github.com/dreamworksanimation/openvdb/releases/tag/v3.1.0) doesn't have the same folder structure. Upgrading to the new 4.0.0 version doesn't work because of the patches you are applying (are they still required?) and I'm not good enough with Cmake to do the required path wrangling to adapt it to the archived zip file. What do you think should be done here? Maybe send me a copy of the zip file?

As a side note, I want to make an OpenFX (OFX) plugin for Cycles that would take an XML file path as parameter and offer clip inputs for all required textures and output a Cryptopmatte clip, beauty pass and other AOVs for further compositing. I am also interested in animation de-noising, network rendering, OpenVDB support, deep sampling output, a principled (Disney) shader for surfaces, volumes/sss and curves, UDIM support, lens/camera shaders. So, almost everything on the roadmap and more! ;-)

Please let me know what to do for OpenVDB. Thanks!

### CODE REVIEW

**Comment by brechtvl** [comment]
Thanks! I've committed the more permanent URLs for HDF5 and Schroedinger and the fix for the Apple issue. I've also committed a switch to the OpenVDB 3.1.0 package from GitHub, which hopefully solves the problem for you.

I can't merge the version upgrades since the versions are intended to be the official ones used for Blender and the same on all platforms. I also can't disable OIIO tools because we use them for image diffs in regression testing.

**Comment by up4** [comment]
hi! thanks for the pull. merry xmas! I have just a quick question. do not answer if you are in vacation, please.

ho do I do an "harvest" pass to put everything in the directories expected by the blender/cycles build?

thanks. merry xmas and happy new year again!

**Comment by brechtvl** [comment]
Run `make install` and the files will be installed to the `CMAKE_INSTALL_PREFIX` path.

**Comment by up4** [comment]
Hello. Happy New Year! So I started back from your repo, apple branch. From scratch. OpenImageIO won't link because of "Undefined symbols for architecture x86_64". It seems like OpenImageIO will not get it's dependencies from the build itself but on the system (it tries to link to things in "/usr/local"). Again, I think some kind of Cmake library search is not working… I attached here my full compile log with the errors at the end. I also posted my intentions with Cycles on the mailing list…

[BlenderDependenciesBuildError.txt.zip](https://github.com/brechtvl/blender_dependencies/files/679816/BlenderDependenciesBuildError.txt.zip)

**Pull request closed without merging**
